[build]
  base = "./"
  publish = "./dist/"
  command = "npm run build"

[build.environment]
  NAME = "Subhasree"
  PIC = "https://res.cloudinary.com/dw2h36vj0/image/upload/v1701486111/qsvfpexrdukdgvxzdfls.jpg"
